### ISSUE TITLE
More information about Javascript

### ISSUE THREAD

**Issue by kshitijlawate** [mailtoharshit/Mint#1]
Hi Harshit, I went through the styleguide. It is really a good start. I do agree using apex:tags is not feasible when developing for Lightning/Mobile or custom UI. 
Though it is a StyleGuide, are you planning to write about JavaScript related stuff. As we know when we are not using any salesforce standard input tags, the whole data transfer to server, validation handling needs to be handled by our javascript code. For my own study I did write some code using angular to perform DML and show the field level validation using JavsScript, however I am not sure if the code is correct (performance and best practice wise).

**Comment by mailtoharshit** [comment]
This is evolving guide, I see high adoption of apex tag in practice by majority of Salesforce developer across the globe, my understanding is that apex tag comes with its own power and limitation at the same time. Down the line, yes this is the plan to lighten up guide with more inclination of javascript for both client and server side handling . Feel free to share your knowledge on gist.github.com and forward the link.
